/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppRequestsIndexRouteImport } from './routes/_app.requests.index'
import { Route as AppCentersIndexRouteImport } from './routes/_app.centers.index'
import { Route as AppCentersIdRouteImport } from './routes/_app.centers.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsIndexRoute = AppRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => AppRoute,
} as any)
const AppCentersIndexRoute = AppCentersIndexRouteImport.update({
  id: '/centers/',
  path: '/centers/',
  getParentRoute: () => AppRoute,
} as any)
const AppCentersIdRoute = AppCentersIdRouteImport.update({
  id: '/centers/$id',
  path: '/centers/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/centers/$id': typeof AppCentersIdRoute
  '/centers/': typeof AppCentersIndexRoute
  '/requests/': typeof AppRequestsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AppIndexRoute
  '/centers/$id': typeof AppCentersIdRoute
  '/centers': typeof AppCentersIndexRoute
  '/requests': typeof AppRequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/centers/$id': typeof AppCentersIdRoute
  '/_app/centers/': typeof AppCentersIndexRoute
  '/_app/requests/': typeof AppRequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/centers/$id' | '/centers/' | '/requests/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/centers/$id' | '/centers' | '/requests'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/'
    | '/_app/centers/$id'
    | '/_app/centers/'
    | '/_app/requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/requests/': {
      id: '/_app/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof AppRequestsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/centers/': {
      id: '/_app/centers/'
      path: '/centers'
      fullPath: '/centers/'
      preLoaderRoute: typeof AppCentersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/centers/$id': {
      id: '/_app/centers/$id'
      path: '/centers/$id'
      fullPath: '/centers/$id'
      preLoaderRoute: typeof AppCentersIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppCentersIdRoute: typeof AppCentersIdRoute
  AppCentersIndexRoute: typeof AppCentersIndexRoute
  AppRequestsIndexRoute: typeof AppRequestsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppCentersIdRoute: AppCentersIdRoute,
  AppCentersIndexRoute: AppCentersIndexRoute,
  AppRequestsIndexRoute: AppRequestsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
